
import os

from PIL import Image
for filename in os.listdir("C:/Users/amjad/OneDrive/Desktop/New folder (2)"): 



    # open an Image file (.bmp,.jpg,.png,.gif) you have in the working folder
    imageFile = "C:/Users/amjad/OneDrive/Desktop/New folder (2)/"+filename
    im1 = Image.open(imageFile)
    # adjust width and height to your needs
    width = 700
    height = 700
    # use one of these filter options to resize the Image
    # cubic spline interpolation in a 4x4 environment
    im5 = im1.resize((width, height), Image.ANTIALIAS)    # best down-sizing filter
    im5.save(filename)
    # optional Image viewer ...
    # Image viewer  i_view32.exe   free download from:  http://www.irfanview.com/
    # avoids the many huge bitmap files generated by PIL's show()